config/routes.rb
Rails.application.routes.draw do
  resources :haikus
  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      match '/haiku' => 'haiku#create', via: :post
      match '/haiku' => 'haiku#index', via: :get
      match '/haiku/:haiku_id/upvote' => 'haiku#upvote', via: :put
      match '/haiku/:haiku_id/downvote' => 'haiku#downvote', via: :put
      match '/haiku/:haiku_id/vote/:vote_id' => 'haiku#delete_vote', via: :delete
    end
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
end

app/models/haiku.rb
class Haiku
  include Mongoid::Document
  include Mongoid::Timestamps
  field :username, type: String
  field :line1, type: String
  field :line2, type: String
  field :line3, type: String
  field :font, type: String
  has_many :votes

  def as_json_for_api(request=nil)
    data = self.as_json
    data['upvotes'] = self.votes.where(direction: 'up').count
    data['downvotes'] = self.votes.where(direction: 'down').count
    if request
      myvote = Vote.where(haiku_id: self.id, source: "#{request.env['HTTP_X_FORWARDED_HOST']}-#{request.env['HTTP_USER_AGENT']}").last
      if myvote
        data['myvote'] = myvote
      end
    end
    data
  end
end

app/models/vote.rb
class Vote
    include Mongoid::Document
    include Mongoid::Timestamps
    belongs_to :haiku
    field :direction  # up or down
    field :source
end

app/controllers/api/v1/haiku_controller.rb
class Api::V1::HaikuController < ApplicationController

  def create
    line1 = params[:line1]
    line2 = params[:line2]
    line3 = params[:line3]
    username = params[:username]
    haiku = Haiku.new({line1: line1, line2: line2, line3: line3, username: username, font: params[:font]})
    haiku.save!
    render json: {haiku: haiku.as_json_for_api}, status: :ok
  end

  def delete_vote
    vote = Vote.find(params[:vote_id])
    vote.destroy!
    haiku = Haiku.find(params[:haiku_id])
    render json: {haiku: haiku.as_json_for_api}, status: :ok
  end

  def upvote
    haiku_id = params[:haiku_id]
    haiku = Haiku.find(haiku_id)
    source = "#{request.env['HTTP_X_FORWARDED_HOST']}-#{request.env['HTTP_USER_AGENT']}"
    vote_check = Vote.where(haiku_id: haiku_id, source: source).last
    if vote_check
      if vote_check.direction == 'down'
        vote_check.direction = 'up'
        vote_check.save!
        render json: {haiku: haiku.reload.as_json_for_api(request)}, status: :ok and return
      else
        render json: {error: 'Only one vote permitted per haiku'}, status: 422 and return
      end
    end
    vote = Vote.new(haiku_id: haiku_id, direction: 'up', source: source)
    vote.save!
    haiku = Haiku.find(params[:haiku_id])
    render json: {haiku: haiku.as_json_for_api(request)}, status: :ok
  end

  def downvote
    haiku_id = params[:haiku_id]
    haiku = Haiku.find(haiku_id)
    source = "#{request.env['HTTP_X_FORWARDED_HOST']}-#{request.env['HTTP_USER_AGENT']}"
    vote_check = Vote.where(haiku_id: haiku_id, source: source).last
    if vote_check
      if vote_check.direction == 'up'
        vote_check.direction = 'down'
        vote_check.save!
        render json: {haiku: haiku.reload.as_json_for_api(request)}, status: :ok and return
      else
        render json: {error: 'Only one vote permitted per haiku'}, status: 422 and return
      end
    end
    vote = Vote.new(haiku_id: haiku_id, direction: 'down', source: source)
    vote.save!
    haiku = Haiku.find(params[:haiku_id])
    render json: {haiku: haiku.as_json_for_api(request)}, status: :ok
  end

  def index
    render json: {haiku: Haiku.all.map{|x| x.as_json_for_api(request)}}, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # skip_before_filter :verify_authenticity_token
 skip_before_action :verify_authenticity_token
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment, notice: "Comment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: "Comment was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:name)
    end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  before_action :set_haiku, only: %i[ show edit update destroy ]

  # GET /haikus
  def index
    @haikus = Haiku.all
  end

  # GET /haikus/1
  def show
  end

  # GET /haikus/new
  def new
    @haiku = Haiku.new
  end

  # GET /haikus/1/edit
  def edit
  end

  # POST /haikus
  def create
    @haiku = Haiku.new(haiku_params)

    if @haiku.save
      redirect_to @haiku, notice: "Haiku was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /haikus/1
  def update
    if @haiku.update(haiku_params)
      redirect_to @haiku, notice: "Haiku was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /haikus/1
  def destroy
    @haiku.destroy
    redirect_to haikus_url, notice: "Haiku was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_haiku
      @haiku = Haiku.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def haiku_params
      params.require(:haiku).permit(:username, :line1, :line2, :line3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Name:</strong>
    <%= comment.name %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/haikus/_form.html.erb
<%= form_with(model: haiku) do |form| %>
  <% if haiku.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(haiku.errors.count, "error") %> prohibited this haiku from being saved:</h2>

      <ul>
        <% haiku.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :line1, style: "display: block" %>
    <%= form.text_area :line1 %>
  </div>

  <div>
    <%= form.label :line2, style: "display: block" %>
    <%= form.text_area :line2 %>
  </div>

  <div>
    <%= form.label :line3, style: "display: block" %>
    <%= form.text_area :line3 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/haikus/_haiku.html.erb
<div id="<%= dom_id haiku %>">
  <p>
    <strong>Username:</strong>
    <%= haiku.username %>
  </p>

  <p>
    <strong>Line1:</strong>
    <%= haiku.line1 %>
  </p>

  <p>
    <strong>Line2:</strong>
    <%= haiku.line2 %>
  </p>

  <p>
    <strong>Line3:</strong>
    <%= haiku.line3 %>
  </p>

</div>

app/views/haikus/edit.html.erb
<h1>Editing haiku</h1>

<%= render "form", haiku: @haiku %>

<br>

<div>
  <%= link_to "Show this haiku", @haiku %> |
  <%= link_to "Back to haikus", haikus_path %>
</div>

app/views/haikus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Haikus</h1>

<div id="haikus">
  <% @haikus.each do |haiku| %>
    <%= render haiku %>
    <p>
      <%= link_to "Show this haiku", haiku %>
    </p>
  <% end %>
</div>

<%= link_to "New haiku", new_haiku_path %>

app/views/haikus/new.html.erb
<h1>New haiku</h1>

<%= render "form", haiku: @haiku %>

<br>

<div>
  <%= link_to "Back to haikus", haikus_path %>
</div>

app/views/haikus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @haiku %>

<div>
  <%= link_to "Edit this haiku", edit_haiku_path(@haiku) %> |
  <%= link_to "Back to haikus", haikus_path %>

  <%= button_to "Destroy this haiku", @haiku, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haiku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>